
    "device" : "cuda"
    "dataloader" :
        "batch_size" : 1
        "dataset" : "unreal_parts"
        "data_dir" : "../simple_data"
        "image_type" : "RGB"
        "obj_class" : "mug"
        "num_epochs": 10
        "workers" : 24
    "model":
        'backbone_name': 'wide_resnet50_2'
        'feature_dim': 256
        'input_dim': 3
        'output_dim': 3
        'device': 'cuda'
        'load_model_path': false
    "sampling": 
        "n_pair" : 0
        "n_nonpair_singleobj" : 0 
        "n_nonpair_bg" : 0

